TOOL_PATH = com/craftinginterpreters/tool/
PACKAGE_PATH = com/craftinginterpreters/lox/

default: compile run

compile:
	javac $(TOOL_PATH)GenerateAst.java

run:
	java $(TOOL_PATH)GenerateAst.java $(PACKAGE_PATH)